apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-kube-dns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cloudflare-kube-dns
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cloudflare-kube-dns-viewer
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudflare-kube-dns
subjects:
  - kind: ServiceAccount
    name: cloudflare-kube-dns
    namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudflare-kube-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloudflare-kube-dns
    spec:
      serviceAccountName: cloudflare-kube-dns
      containers:
        - name: cloudflare-kube-dns
          image: segator/cloudflare-kube-dns
          imagePullPolicy: Always
          env:
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-external-dns-secret
                  key: api
            - name: CF_API_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudflare-external-dns-secret
                  key: mail
            - name: CF_API_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-external-dns-secret
                  key: domain